knp_snappy:
    pdf:
        enabled: true
        binary: '%env(resolve:WKHTMLTOPDF_PATH)%'
        options:
            encoding: 'UTF-8'
            enable-local-file-access: true
    image:
        enabled: true
        binary: '%env(resolve:WKHTMLTOIMAGE_PATH)%'
        options: []
