vich_uploader:
    db_driver: orm
    mappings:
        feed_post_images:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

